### ISSUE TITLE
no linkattacher_msg.config.cmake

### ISSUE THREAD

**Issue by 8LTB8smile8angel8** [IFRA-Cranfield/ros2_SimRealRobotControl#2]
![87303dd2b20e0e96e1516590d5d023a](https://github.com/IFRA-Cranfield/ros2_SimRealRobotControl/assets/139226775/32fcbf70-43dc-4a35-80eb-b3a4ee82f08c)
hi, man
i meet a question,how can i solve it?
Could you waste some time to help me?
Thank U,Sir.

**Comment by MikelBueno** [comment]
Hi @8LTB8smile8angel8 , 

This issue can be easily fixed by installing the IFRA_LinkAttacher ROS2 repository, which is needed to compile and use ros2_SimRealRobotControl. The instructions to install this are included in the README.md file (step N4), but please find them below just in case:
```sh
cd ~/dev_ws/src
git clone https://github.com/IFRA-Cranfield/IFRA_LinkAttacher.git
cd ~/dev_ws
colcon build 
```

Best regards,
Mikel Bueno
IFRA Cranfield
